package nl.joey.universe.repository

case class PlanetData(name:String,
                      textY: Float,
                      a0: Float,
                      at: Float,
                      e0: Float,
                      et: Float,
                      I0: Float,
                      It: Float,
                      L0: Float,
                      Lt: Float,
                      w0: Float,
                      wt: Float,
                      o0: Float,
                      ot: Float,
                      b: Option[Float] = None,
                      c: Option[Float] = None,
                      s: Option[Float] = None,
                      f: Option[Float] = None)
